button.group:
  base:
    - "flex w-fit items-stretch"
    - "[&>*]:focus-visible:z-10 [&>*]:focus-visible:relative"
    - "has-[>[data-slot=button-group]]:gap-2"
  variants:
    orientation:
      horizontal:
        - "flex-row"
        - "[&>*:not(:first-child)]:rounded-l-none"
        - "[&>*:not(:first-child)]:border-l-0"
        - "[&>*:not(:last-child)]:rounded-r-none"
      vertical:
        - "flex-col"
        - "[&>*:not(:first-child)]:rounded-t-none"
        - "[&>*:not(:first-child)]:border-t-0"
        - "[&>*:not(:last-child)]:rounded-b-none"
  defaultVariants:
    orientation: horizontal

button.group.separator:
  base:
    - "bg-input relative !m-0 self-stretch"
    - "data-[orientation=vertical]:h-auto"
  variants:
    orientation:
      horizontal: "w-px"
      vertical: "h-px"
  defaultVariants:
    orientation: vertical