dialog:
  base:
  defaultVariants: {}

dialog.native:
  base:
    - "z-50 m-auto duration-200 bg-transparent ease-out"
    - "backdrop:bg-black/80 backdrop:transition-all backdrop:duration-200"
    - "data-[closed]:opacity-0 data-[closed]:scale-95"
    - "data-[leave]:opacity-0 data-[leave]:scale-95 data-[leave]:duration-150"
    - "data-[leave]:backdrop:bg-black/0 data-[leave]:backdrop:duration-150"
    - "data-[transition]:transition-all"
  defaultVariants: {}

dialog.content:
  base:
    - "relative border-border bg-background text-foreground w-full max-w-lg gap-4 border p-6 shadow-lg rounded-lg grid gap-4"
  defaultVariants: {}

dialog.header:
  base:
    - "flex flex-col space-y-1.5 text-center sm:text-left"
  defaultVariants: {}

dialog.title:
  base:
    - "text-lg font-semibold leading-none tracking-tight"
  defaultVariants: {}

dialog.description:
  base:
    - "text-muted-foreground text-sm"
  defaultVariants: {}

dialog.footer:
  base:
    - "flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2"
  defaultVariants: {}

dialog.close:
  base:
    - "border-input bg-background ring-offset-background absolute right-4 top-4 rounded-sm opacity-70 transition-opacity"
    - "hover:bg-accent hover:text-accent-foreground hover:opacity-100"
    - "focus:ring-ring focus:outline-none focus:ring-2 focus:ring-offset-2"
    - "disabled:pointer-events-none"
  defaultVariants: {}