dialog:
  base:
  defaultVariants: {}

dialog.native:
  base:
    - "relative z-50 m-auto bg-transparent transition-all "
    - "backdrop:bg-black/50"
    - "data-[enter]:animate-in data-[leave]:animate-out"
    - "data-[leave]:fade-out-0 data-[enter]:fade-in-0"
    - "data-[closed]:opacity-0"
    - "backdrop:data-[enter]:animate-in backdrop:data-[leave]:animate-out"
    - "backdrop:data-[leave]:fade-out-0 backdrop:data-[enter]:fade-in-0"
    - "backdrop:data-[closed]:opacity-0"
  defaultVariants: {}

dialog.content:
  base:
    - "relative border-border bg-background text-foreground w-full max-w-lg gap-4 border p-6 shadow-lg rounded-lg grid gap-4 transition-all duration-200"
    - "data-[enter]:animate-in data-[leave]:animate-out data-[enter]:zoom-in-95"
    - "data-[leave]:fade-out-0 data-[enter]:fade-in-0 data-[leave]:zoom-out-95"
    - "data-[closed]:opacity-0 data-[closed]:scale-95"
  defaultVariants: {}

dialog.header:
  base:
    - "flex flex-col space-y-1.5 text-center"
    - "sm:text-left"
  defaultVariants: {}

dialog.title:
  base:
    - "text-lg font-semibold leading-none tracking-tight"
  defaultVariants: {}

dialog.description:
  base:
    - "text-muted-foreground text-sm"
  defaultVariants: {}

dialog.footer:
  base:
    - "flex flex-col-reverse"
    - "sm:flex-row sm:justify-end sm:space-x-2"
  defaultVariants: {}

dialog.close_icon:
  base:
    - "border-input bg-background ring-offset-background absolute right-4 top-4 rounded-sm opacity-70 transition-opacity"
    - "hover:bg-accent hover:text-accent-foreground hover:opacity-100"
    - "focus:ring-ring focus:outline-none focus:ring-2 focus:ring-offset-2"
    - "disabled:pointer-events-none"
  defaultVariants: {}
