# Drawer styles are now handled by Lit components with CSS-in-JS
# These are utility styles for header/footer components that are still regular divs

drawer.header:
  base:
    - "hui-drawer-header"
  defaultVariants: {}

drawer.footer:
  base:
    - "hui-drawer-footer"
  defaultVariants: {}

# Legacy styles for backward compatibility (if needed)
drawer:
  base:
    - "hui-drawer-legacy"
  defaultVariants: {}

drawer.container:
  base:
    - "hui-drawer-container-legacy"
  defaultVariants: {}

drawer.overlay:
  base:
    - "hui-drawer-overlay-legacy"
  defaultVariants: {}

drawer.content:
  base:
    - "hui-drawer-content-legacy"
  defaultVariants: {}

drawer.handle:
  base:
    - "hui-drawer-handle-legacy"
  defaultVariants: {}

drawer.title:
  base:
    - "hui-drawer-title-legacy"
  defaultVariants: {}

drawer.description:
  base:
    - "hui-drawer-description-legacy"
  defaultVariants: {}

drawer.close:
  base:
    - "hui-drawer-close-legacy"
  defaultVariants: {}

drawer.trigger:
  base:
    - "hui-drawer-trigger-legacy"
  defaultVariants: {}