dropdown-menu:
  base:
  defaultVariants: {}

dropdown-menu.root:
  base:
    - "fixed overflow-visible bg-transparent"
    - "focus:outline-none"
  defaultVariants: {}

dropdown-menu.content:
  base:
    - "isolate relative bg-popover text-popover-foreground border border-border rounded-md shadow-md min-w-[12rem] p-1"
    - "focus:outline-none"
    - "data-[closed]:opacity-0 data-[closed]:scale-95"
    - "data-[enter]:animate-in data-[enter]:fade-in-0 data-[enter]:zoom-in-95"
    - "data-[leave]:animate-out data-[leave]:fade-out-0 data-[leave]:zoom-out-95"
    - "data-[transition]:transition-gpu data-[transition]:duration-180"
    - "data-[side=top]:origin-bottom data-[side=top]:slide-in-from-bottom-2"
    - "data-[side=top-start]:origin-bottom data-[side=top-start]:slide-in-from-bottom-2"
    - "data-[side=top-end]:origin-bottom data-[side=top-end]:slide-in-from-bottom-2"
    - "data-[side=bottom]:origin-top data-[side=bottom]:slide-in-from-top-2"
    - "data-[side=bottom-start]:origin-top data-[side=bottom-start]:slide-in-from-top-2"
    - "data-[side=bottom-end]:origin-top data-[side=bottom-end]:slide-in-from-top-2"
    - "data-[side=left]:origin-right data-[side=left]:slide-in-from-right-2"
    - "data-[side=left-start]:origin-right data-[side=left-start]:slide-in-from-right-2"
    - "data-[side=left-end]:origin-right data-[side=left-end]:slide-in-from-right-2"
    - "data-[side=right]:origin-left data-[side=right]:slide-in-from-left-2"
    - "data-[side=right-start]:origin-left data-[side=right-start]:slide-in-from-left-2"
    - "data-[side=right-end]:origin-left data-[side=right-end]:slide-in-from-left-2"
  defaultVariants: {}

dropdown-menu.item:
  base:
    - "relative flex cursor-pointer select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none"
    - "transition-colors duration-100"
    - "focus:bg-accent focus:text-accent-foreground"
    - "hover:bg-accent hover:text-accent-foreground"
    - "data-[disabled]:pointer-events-none data-[disabled]:opacity-50"
    - "[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0"
  defaultVariants: {}

dropdown-menu.label:
  base:
    - "px-2 py-1.5 text-sm font-semibold text-foreground"
  defaultVariants: {}

dropdown-menu.separator:
  base:
    - "-mx-1 my-1 h-px bg-border"
  defaultVariants: {}

dropdown-menu.shortcut:
  base:
    - "ml-auto text-xs tracking-widest text-muted-foreground"
  defaultVariants: {}

dropdown-menu.group:
  base:
  defaultVariants: {}
