popover:
  base:
  defaultVariants: {}

popover.root:
  base:
    - "fixed overflow-visible bg-transparent"
    - "focus:outline-none"
  defaultVariants: {}

popover.content:
  base:
    - "bg-popover text-popover-foreground border border-border rounded-md shadow-md p-4 "
    - "focus:outline-none"
    - "data-[closed]:opacity-0 data-[closed]:scale-95"
    - "data-[enter]:animate-in data-[enter]:fade-in-0 data-[enter]:zoom-in-95"
    - "data-[leave]:animate-in data-[leave]:fade-out-0 data-[leave]:zoom-out-95"
    - "data-[transition]:transition-gpu data-[transition]:duration-180"
    - "data-[side=top]:origin-bottom data-[side=top]:slide-in-from-bottom-2"
    - "data-[side=top-start]:origin-bottom data-[side=top-start]:slide-in-from-bottom-2"
    - "data-[side=top-end]:origin-bottom data-[side=top-end]:slide-in-from-bottom-2"
    - "data-[side=bottom]:origin-top data-[side=bottom]:slide-in-from-top-2"
    - "data-[side=bottom-start]:origin-top data-[side=bottom-start]:slide-in-from-top-2"
    - "data-[side=bottom-end]:origin-top data-[side=bottom-end]:slide-in-from-top-2"
    - "data-[side=left]:origin-right data-[side=left]:slide-in-from-right-2"
    - "data-[side=left-start]:origin-right data-[side=left-start]:slide-in-from-right-2"
    - "data-[side=left-end]:origin-right data-[side=left-end]:slide-in-from-right-2"
    - "data-[side=right]:origin-left data-[side=right]:slide-in-from-left-2"
    - "data-[side=right-start]:origin-left data-[side=right-start]:slide-in-from-left-2"
    - "data-[side=right-end]:origin-left data-[side=right-end]:slide-in-from-left-2"
  defaultVariants: {}

popover.close:
  base:
    - "inline-flex items-center justify-center rounded-sm text-sm font-medium transition-colors"
    - "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
    - "disabled:pointer-events-none disabled:opacity-50"
    - "hover:bg-accent hover:text-accent-foreground"
    - "h-8 w-8"
  defaultVariants: {}

popover.arrow:
  base:
    - "absolute size-4 bg-red-500"
    - "data-[side=top]:top-full"
    - "data-[side=top-start]:top-full"
    - "data-[side=top-end]:top-full"
    - "data-[side=bottom]:bottom-full"
    - "data-[side=bottom-start]:bottom-full"
    - "data-[side=bottom-end]:bottom-full"
    - "data-[side=left]:left-full"
    - "data-[side=left-start]:left-full"
    - "data-[side=left-end]:left-full"
    - "data-[side=right]:right-full"
    - "data-[side=right-start]:right-full"
    - "data-[side=right-end]:right-full"
  defaultVariants: {}